name:
  Unit Tests
  
on:
  push:
    branches:
    - main
  pull_request:
    branches:    
      - main
    
jobs:
  test:
    name: run test
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v1
    - name: npm install, build and test
      run: |
        cd linkedin-clone
        npm install
        npm test
    
